version: '3.2'
services:
  namesrv:
    container_name: rocketmq-namesvr
    image: 'registry.cn-shenzhen.aliyuncs.com/iotimc-cxj/rocketmq-namesvr'
    environment:
      LANG: C.UTF-8
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ROCKETMQ_HOME: /opt/rocketmq-4.1.0-incubating
    ports:
      - '9876:9877'
    volumes:
      - '/opt/logs'
      - '/opt/store'
    networks:
      - elsi-trunk
  broker:
    container_name: rocketmq-broker
    image: 'registry.cn-shenzhen.aliyuncs.com/iotimc-cxj/rocketmq-broker'
    environment:
      NAMESRV_ADDR: namesrv:9877
      LANG: C.UTF-8
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ROCKETMQ_HOME: /opt/rocketmq-4.1.0-incubating
    ports:
      - '10909:10929'
      - '10911:10931'
    volumes:
      - '/opt/logs'
      - '/opt/store'
    depends_on:
      - namesrv
    networks:
      - elsi-trunk
networks:
  elsi-trunk:
    external: true