version: '3.2'
services:
  broker:
    container_name: rocketmq-broker
    image: 'registry.cn-shenzhen.aliyuncs.com/iotimc-cxj/rocketmq-broker'
    environment:
      NAMESRV_ADDR: 127.0.0.1:9876
      LANG: C.UTF-8
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ROCKETMQ_HOME: /opt/rocketmq-4.1.0-incubating
    ports:
      - '10909:10909'
      - '10911:10911'
    volumes:
      - '/opt/logs'
      - '/opt/store'
    networks:
      - elsi-trunk
networks:
  elsi-trunk:
    external: true