version: '2'
services:
  namesrv:
    image: 'registry.cn-shenzhen.aliyuncs.com/iotimc-cxj/rocketmq-namesvr:latest'
    ports:
      - 9876:9876
    volumes:
      - ./namesrv/logs:/opt/logs
      - ./namesrv/store:/opt/store
  broker:
    image: 'registry.cn-shenzhen.aliyuncs.com/iotimc-cxj/rocketmq-broker:latest'
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./broker/logs:/opt/logs
      - ./broker/store:/opt/store
    depends_on:
      - namesrv
